var searchData=
[
  ['tanhcpufunctor',['TanhCPUFunctor',['../structcaffe2_1_1TanhCPUFunctor.html',1,'caffe2']]],
  ['tanhgradientcpufunctor',['TanhGradientCPUFunctor',['../structcaffe2_1_1TanhGradientCPUFunctor.html',1,'caffe2']]],
  ['task',['Task',['../structcaffe2_1_1gpu__single__thread_1_1Task.html',1,'caffe2::gpu_single_thread']]],
  ['task',['Task',['../structcaffe2_1_1Task.html',1,'caffe2']]],
  ['taskthreadpool',['TaskThreadPool',['../classcaffe2_1_1TaskThreadPool.html#af1d3188477c3e1086a68fb487288948c',1,'caffe2::TaskThreadPool']]],
  ['taskthreadpool',['TaskThreadPool',['../classcaffe2_1_1TaskThreadPool.html',1,'caffe2']]],
  ['tensor',['Tensor',['../classcaffe2_1_1Tensor.html',1,'caffe2']]],
  ['tensor',['Tensor',['../structTensor.html',1,'Tensor'],['../classcaffe2_1_1Tensor.html#a813559c5a8dbcdb7743d333d24f05481',1,'caffe2::Tensor::Tensor()'],['../classcaffe2_1_1Tensor.html#a4033b18347ac94c18f80d7b2a1d2cb16',1,'caffe2::Tensor::Tensor(const vector&lt; TIndex &gt; &amp;dims)'],['../classcaffe2_1_1Tensor.html#a553e23abde50c8573ef0bc467876ebb7',1,'caffe2::Tensor::Tensor(const Tensor&lt; SrcContext &gt; &amp;src, ContextForCopy *context)'],['../classcaffe2_1_1Tensor.html#a43bdfe596b5a6dfcf5232adf9972c5ad',1,'caffe2::Tensor::Tensor(const Tensor&lt; SrcContext &gt; &amp;src)'],['../classcaffe2_1_1Tensor.html#ad17896c358189b7a0ef67fffd62663e9',1,'caffe2::Tensor::Tensor(const vector&lt; TIndex &gt; &amp;dims, const vector&lt; T &gt; &amp;values, Context *context)'],['../classcaffe2_1_1Tensor.html#a02d3a30f2343c0ec0a8af285807ad984',1,'caffe2::Tensor::Tensor(const T &amp;value, Context *context)']]],
  ['tensor_3c_20caffe2_3a_3acpucontext_20_3e',['Tensor&lt; caffe2::CPUContext &gt;',['../classcaffe2_1_1Tensor.html',1,'caffe2']]],
  ['tensor_3c_20caffe2_3a_3acudacontext_20_3e',['Tensor&lt; caffe2::CUDAContext &gt;',['../classcaffe2_1_1Tensor.html',1,'caffe2']]],
  ['tensor_3c_20cpucontext_20_3e',['Tensor&lt; CPUContext &gt;',['../classcaffe2_1_1Tensor.html',1,'caffe2']]],
  ['tensor_3c_20cudacontext_20_3e',['Tensor&lt; CUDAContext &gt;',['../classcaffe2_1_1Tensor.html',1,'caffe2']]],
  ['tensorcoreavailable',['TensorCoreAvailable',['../namespacecaffe2.html#ac9185fa7304a1a5553a05fee40830c43',1,'caffe2']]],
  ['tensordescriptors',['TensorDescriptors',['../classcaffe2_1_1detail_1_1TensorDescriptors.html',1,'caffe2::detail']]],
  ['tensordeserializer',['TensorDeserializer',['../classcaffe2_1_1TensorDeserializer.html',1,'caffe2']]],
  ['tensorinferencefunction',['TensorInferenceFunction',['../classcaffe2_1_1OpSchema.html#a77b556c1f29217a499b13cbcc18446c7',1,'caffe2::OpSchema']]],
  ['tensorprinter',['TensorPrinter',['../classcaffe2_1_1TensorPrinter.html',1,'caffe2']]],
  ['tensorprotosdbinput',['TensorProtosDBInput',['../classcaffe2_1_1TensorProtosDBInput.html',1,'caffe2']]],
  ['tensorserializer',['TensorSerializer',['../classcaffe2_1_1TensorSerializer.html',1,'caffe2']]],
  ['tensortypes',['TensorTypes',['../structcaffe2_1_1TensorTypes.html',1,'caffe2']]],
  ['tensortypes2',['TensorTypes2',['../structcaffe2_1_1TensorTypes2.html',1,'caffe2']]],
  ['test_5fbenchmark',['TEST_Benchmark',['../classcaffe2_1_1NetBase.html#a69aed01ddcd98e7fa13b174c4cd134a8',1,'caffe2::NetBase::TEST_Benchmark()'],['../classcaffe2_1_1DAGNetBase.html#a6d325ca3e2e4557bee26b773757465e3',1,'caffe2::DAGNetBase::TEST_Benchmark()'],['../classcaffe2_1_1SimpleNet.html#a130a5cdba80ddb6e52bd45c0da276e26',1,'caffe2::SimpleNet::TEST_Benchmark()'],['../classcaffe2_1_1AsyncSimpleNet.html#a1766f137a639177634af5de98d8f60e7',1,'caffe2::AsyncSimpleNet::TEST_Benchmark()']]],
  ['textfilereaderinstance',['TextFileReaderInstance',['../structcaffe2_1_1TextFileReaderInstance.html',1,'caffe2']]],
  ['textfilereaderreadop',['TextFileReaderReadOp',['../classcaffe2_1_1TextFileReaderReadOp.html',1,'caffe2']]],
  ['texture_5fattachment',['texture_attachment',['../structGLFilter_1_1texture__attachment.html',1,'GLFilter']]],
  ['threadedrecurrentnetworkexecutor',['ThreadedRecurrentNetworkExecutor',['../classcaffe2_1_1ThreadedRecurrentNetworkExecutor.html',1,'caffe2']]],
  ['threadlocalcudaobjects',['ThreadLocalCUDAObjects',['../classcaffe2_1_1ThreadLocalCUDAObjects.html',1,'caffe2']]],
  ['threadpool',['ThreadPool',['../classcaffe2_1_1ThreadPool.html',1,'caffe2']]],
  ['throwinthetowelifgradientiscalled',['ThrowInTheTowelIfGradientIsCalled',['../structcaffe2_1_1ThrowInTheTowelIfGradientIsCalled.html',1,'caffe2']]],
  ['tile_5fdescriptor',['tile_descriptor',['../structtile__descriptor.html',1,'']]],
  ['tilegradientop',['TileGradientOp',['../classcaffe2_1_1TileGradientOp.html',1,'caffe2']]],
  ['tileop',['TileOp',['../classcaffe2_1_1TileOp.html',1,'caffe2']]],
  ['timeobserver',['TimeObserver',['../classcaffe2_1_1TimeObserver.html',1,'caffe2']]],
  ['timeobserver_3c_20netbase_20_3e',['TimeObserver&lt; NetBase &gt;',['../classcaffe2_1_1TimeObserver_3_01NetBase_01_4.html',1,'caffe2']]],
  ['timeobserver_3c_20operatorbase_20_3e',['TimeObserver&lt; OperatorBase &gt;',['../classcaffe2_1_1TimeObserver_3_01OperatorBase_01_4.html',1,'caffe2']]],
  ['timeobserverbase',['TimeObserverBase',['../classcaffe2_1_1TimeObserverBase.html',1,'caffe2']]],
  ['timeobserverbase_3c_20netbase_20_3e',['TimeObserverBase&lt; NetBase &gt;',['../classcaffe2_1_1TimeObserverBase.html',1,'caffe2']]],
  ['timeobserverbase_3c_20operatorbase_20_3e',['TimeObserverBase&lt; OperatorBase &gt;',['../classcaffe2_1_1TimeObserverBase.html',1,'caffe2']]],
  ['timer',['Timer',['../classcaffe2_1_1Timer.html',1,'caffe2']]],
  ['timerbeginop',['TimerBeginOp',['../structcaffe2_1_1TimerBeginOp.html',1,'caffe2']]],
  ['timerendop',['TimerEndOp',['../structcaffe2_1_1TimerEndOp.html',1,'caffe2']]],
  ['timergetandendop',['TimerGetAndEndOp',['../structcaffe2_1_1TimerGetAndEndOp.html',1,'caffe2']]],
  ['timergetop',['TimerGetOp',['../structcaffe2_1_1TimerGetOp.html',1,'caffe2']]],
  ['timerinstance',['TimerInstance',['../classcaffe2_1_1TimerInstance.html',1,'caffe2']]],
  ['token',['Token',['../structcaffe2_1_1Token.html',1,'caffe2']]],
  ['tokenizedstring',['TokenizedString',['../classcaffe2_1_1TokenizedString.html',1,'caffe2']]],
  ['tokenizer',['Tokenizer',['../classcaffe2_1_1Tokenizer.html',1,'caffe2']]],
  ['topkgradientop',['TopKGradientOp',['../classcaffe2_1_1TopKGradientOp.html',1,'caffe2']]],
  ['topkop',['TopKOp',['../classcaffe2_1_1TopKOp.html',1,'caffe2']]],
  ['tovectortindex',['ToVectorTIndex',['../namespacecaffe2.html#a591122a8091d7c58df32810129874cb2',1,'caffe2']]],
  ['transaction',['Transaction',['../classcaffe2_1_1db_1_1Transaction.html',1,'caffe2::db']]],
  ['transform',['Transform',['../classcaffe2_1_1Transform.html',1,'caffe2']]],
  ['transposeop',['TransposeOp',['../classcaffe2_1_1TransposeOp.html',1,'caffe2']]],
  ['treecursor',['TreeCursor',['../classcaffe2_1_1dataset__ops_1_1TreeCursor.html',1,'caffe2::dataset_ops']]],
  ['treeiterator',['TreeIterator',['../classcaffe2_1_1dataset__ops_1_1TreeIterator.html',1,'caffe2::dataset_ops']]],
  ['treewalker',['TreeWalker',['../classcaffe2_1_1dataset__ops_1_1TreeWalker.html',1,'caffe2::dataset_ops']]],
  ['ttcontractiongradientop',['TTContractionGradientOp',['../classcaffe2_1_1TTContractionGradientOp.html',1,'caffe2']]],
  ['ttcontractionop',['TTContractionOp',['../classcaffe2_1_1TTContractionOp.html',1,'caffe2']]],
  ['ttlineargradientop',['TTLinearGradientOp',['../classcaffe2_1_1TTLinearGradientOp.html',1,'caffe2']]],
  ['ttlinearop',['TTLinearOp',['../classcaffe2_1_1TTLinearOp.html',1,'caffe2']]],
  ['ttpadgradientop',['TTPadGradientOp',['../classcaffe2_1_1TTPadGradientOp.html',1,'caffe2']]],
  ['ttpadop',['TTPadOp',['../classcaffe2_1_1TTPadOp.html',1,'caffe2']]],
  ['type',['Type',['../structGLTexture_1_1Type.html',1,'GLTexture']]],
  ['typemeta',['TypeMeta',['../classcaffe2_1_1TypeMeta.html#a9f8e66d75448302751da57b8df1c906f',1,'caffe2::TypeMeta::TypeMeta()'],['../classcaffe2_1_1TypeMeta.html#aa110c2a289bafa97472342f25755a10f',1,'caffe2::TypeMeta::TypeMeta(const TypeMeta &amp;src)']]],
  ['typemeta',['TypeMeta',['../classcaffe2_1_1TypeMeta.html',1,'caffe2']]],
  ['typename',['TypeName',['../classcaffe2_1_1Blob.html#a2a807ee90e38f2f0261f8c1f6709727a',1,'caffe2::Blob']]],
  ['typenameregisterer',['TypeNameRegisterer',['../structcaffe2_1_1TypeNameRegisterer.html',1,'caffe2']]],
  ['typenametraits',['TypeNameTraits',['../structcaffe2_1_1TypeNameTraits.html',1,'caffe2']]],
  ['typenametraits_3c_20int32_5ft_20_3e',['TypeNameTraits&lt; int32_t &gt;',['../structcaffe2_1_1TypeNameTraits_3_01int32__t_01_4.html',1,'caffe2']]],
  ['typenametraits_3c_20int64_5ft_20_3e',['TypeNameTraits&lt; int64_t &gt;',['../structcaffe2_1_1TypeNameTraits_3_01int64__t_01_4.html',1,'caffe2']]]
];
