var searchData=
[
  ['tanhcpufunctor',['TanhCPUFunctor',['../structcaffe2_1_1_tanh_c_p_u_functor.html',1,'caffe2']]],
  ['tanhgradientcpufunctor',['TanhGradientCPUFunctor',['../structcaffe2_1_1_tanh_gradient_c_p_u_functor.html',1,'caffe2']]],
  ['task',['Task',['../structcaffe2_1_1gpu__single__thread_1_1_task.html',1,'caffe2::gpu_single_thread']]],
  ['task',['Task',['../structcaffe2_1_1_task.html',1,'caffe2']]],
  ['taskthreadpool',['TaskThreadPool',['../classcaffe2_1_1_task_thread_pool.html#af1d3188477c3e1086a68fb487288948c',1,'caffe2::TaskThreadPool']]],
  ['taskthreadpool',['TaskThreadPool',['../classcaffe2_1_1_task_thread_pool.html',1,'caffe2']]],
  ['tensor',['Tensor',['../struct_tensor.html',1,'Tensor'],['../classcaffe2_1_1_tensor.html#a813559c5a8dbcdb7743d333d24f05481',1,'caffe2::Tensor::Tensor()'],['../classcaffe2_1_1_tensor.html#a4033b18347ac94c18f80d7b2a1d2cb16',1,'caffe2::Tensor::Tensor(const vector&lt; TIndex &gt; &amp;dims)'],['../classcaffe2_1_1_tensor.html#a553e23abde50c8573ef0bc467876ebb7',1,'caffe2::Tensor::Tensor(const Tensor&lt; SrcContext &gt; &amp;src, ContextForCopy *context)'],['../classcaffe2_1_1_tensor.html#a43bdfe596b5a6dfcf5232adf9972c5ad',1,'caffe2::Tensor::Tensor(const Tensor&lt; SrcContext &gt; &amp;src)'],['../classcaffe2_1_1_tensor.html#ad17896c358189b7a0ef67fffd62663e9',1,'caffe2::Tensor::Tensor(const vector&lt; TIndex &gt; &amp;dims, const vector&lt; T &gt; &amp;values, Context *context)'],['../classcaffe2_1_1_tensor.html#a02d3a30f2343c0ec0a8af285807ad984',1,'caffe2::Tensor::Tensor(const T &amp;value, Context *context)']]],
  ['tensor',['Tensor',['../classcaffe2_1_1_tensor.html',1,'caffe2']]],
  ['tensor_3c_20caffe2_3a_3acpucontext_20_3e',['Tensor&lt; caffe2::CPUContext &gt;',['../classcaffe2_1_1_tensor.html',1,'caffe2']]],
  ['tensor_3c_20caffe2_3a_3acudacontext_20_3e',['Tensor&lt; caffe2::CUDAContext &gt;',['../classcaffe2_1_1_tensor.html',1,'caffe2']]],
  ['tensor_3c_20cpucontext_20_3e',['Tensor&lt; CPUContext &gt;',['../classcaffe2_1_1_tensor.html',1,'caffe2']]],
  ['tensor_3c_20cudacontext_20_3e',['Tensor&lt; CUDAContext &gt;',['../classcaffe2_1_1_tensor.html',1,'caffe2']]],
  ['tensor_3c_20glcontext_20_3e',['Tensor&lt; GLContext &gt;',['../classcaffe2_1_1_tensor.html',1,'caffe2']]],
  ['tensorcoreavailable',['TensorCoreAvailable',['../namespacecaffe2.html#ac9185fa7304a1a5553a05fee40830c43',1,'caffe2']]],
  ['tensordescriptors',['TensorDescriptors',['../classcaffe2_1_1detail_1_1_tensor_descriptors.html',1,'caffe2::detail']]],
  ['tensordeserializer',['TensorDeserializer',['../classcaffe2_1_1_tensor_deserializer.html',1,'caffe2']]],
  ['tensorinferencefunction',['TensorInferenceFunction',['../classcaffe2_1_1_op_schema.html#a77b556c1f29217a499b13cbcc18446c7',1,'caffe2::OpSchema']]],
  ['tensorprinter',['TensorPrinter',['../classcaffe2_1_1_tensor_printer.html',1,'caffe2']]],
  ['tensorprotosdbinput',['TensorProtosDBInput',['../classcaffe2_1_1_tensor_protos_d_b_input.html',1,'caffe2']]],
  ['tensorserializer',['TensorSerializer',['../classcaffe2_1_1_tensor_serializer.html',1,'caffe2']]],
  ['tensortypes',['TensorTypes',['../structcaffe2_1_1_tensor_types.html',1,'caffe2']]],
  ['tensortypes2',['TensorTypes2',['../structcaffe2_1_1_tensor_types2.html',1,'caffe2']]],
  ['test_5fbenchmark',['TEST_Benchmark',['../classcaffe2_1_1_net_base.html#a69aed01ddcd98e7fa13b174c4cd134a8',1,'caffe2::NetBase::TEST_Benchmark()'],['../classcaffe2_1_1_d_a_g_net_base.html#a6d325ca3e2e4557bee26b773757465e3',1,'caffe2::DAGNetBase::TEST_Benchmark()'],['../classcaffe2_1_1_simple_net.html#a130a5cdba80ddb6e52bd45c0da276e26',1,'caffe2::SimpleNet::TEST_Benchmark()'],['../classcaffe2_1_1_async_simple_net.html#a1766f137a639177634af5de98d8f60e7',1,'caffe2::AsyncSimpleNet::TEST_Benchmark()'],['../classcaffe2_1_1_g_l_net.html#a81ffaab5835f98682674b5e4f8e57a20',1,'caffe2::GLNet::TEST_Benchmark()']]],
  ['textfilereaderinstance',['TextFileReaderInstance',['../structcaffe2_1_1_text_file_reader_instance.html',1,'caffe2']]],
  ['textfilereaderreadop',['TextFileReaderReadOp',['../classcaffe2_1_1_text_file_reader_read_op.html',1,'caffe2']]],
  ['texture_5fattachment',['texture_attachment',['../struct_g_l_filter_1_1texture__attachment.html',1,'GLFilter']]],
  ['threadedrecurrentnetworkexecutor',['ThreadedRecurrentNetworkExecutor',['../classcaffe2_1_1_threaded_recurrent_network_executor.html',1,'caffe2']]],
  ['threadlocalcudaobjects',['ThreadLocalCUDAObjects',['../classcaffe2_1_1_thread_local_c_u_d_a_objects.html',1,'caffe2']]],
  ['threadpool',['ThreadPool',['../classcaffe2_1_1_thread_pool.html',1,'caffe2']]],
  ['thresholdedrelugradientop',['ThresholdedReluGradientOp',['../classcaffe2_1_1_thresholded_relu_gradient_op.html',1,'caffe2']]],
  ['thresholdedreluop',['ThresholdedReluOp',['../classcaffe2_1_1_thresholded_relu_op.html',1,'caffe2']]],
  ['throwinthetowelifgradientiscalled',['ThrowInTheTowelIfGradientIsCalled',['../structcaffe2_1_1_throw_in_the_towel_if_gradient_is_called.html',1,'caffe2']]],
  ['tile_5fdescriptor',['tile_descriptor',['../structtile__descriptor.html',1,'']]],
  ['tilegradientop',['TileGradientOp',['../classcaffe2_1_1_tile_gradient_op.html',1,'caffe2']]],
  ['tileop',['TileOp',['../classcaffe2_1_1_tile_op.html',1,'caffe2']]],
  ['timecounter',['TimeCounter',['../classcaffe2_1_1_time_counter.html',1,'caffe2']]],
  ['timeobserver',['TimeObserver',['../classcaffe2_1_1_time_observer.html',1,'caffe2']]],
  ['timeoperatorobserver',['TimeOperatorObserver',['../classcaffe2_1_1_time_operator_observer.html',1,'caffe2']]],
  ['timer',['Timer',['../classcaffe2_1_1_timer.html',1,'caffe2']]],
  ['timerbeginop',['TimerBeginOp',['../structcaffe2_1_1_timer_begin_op.html',1,'caffe2']]],
  ['timerendop',['TimerEndOp',['../structcaffe2_1_1_timer_end_op.html',1,'caffe2']]],
  ['timergetandendop',['TimerGetAndEndOp',['../structcaffe2_1_1_timer_get_and_end_op.html',1,'caffe2']]],
  ['timergetop',['TimerGetOp',['../structcaffe2_1_1_timer_get_op.html',1,'caffe2']]],
  ['timerinstance',['TimerInstance',['../classcaffe2_1_1_timer_instance.html',1,'caffe2']]],
  ['token',['Token',['../structcaffe2_1_1_token.html',1,'caffe2']]],
  ['tokenizedstring',['TokenizedString',['../classcaffe2_1_1_tokenized_string.html',1,'caffe2']]],
  ['tokenizer',['Tokenizer',['../classcaffe2_1_1_tokenizer.html',1,'caffe2']]],
  ['topkgradientop',['TopKGradientOp',['../classcaffe2_1_1_top_k_gradient_op.html',1,'caffe2']]],
  ['topkop',['TopKOp',['../classcaffe2_1_1_top_k_op.html',1,'caffe2']]],
  ['tovectortindex',['ToVectorTIndex',['../namespacecaffe2.html#a591122a8091d7c58df32810129874cb2',1,'caffe2']]],
  ['transaction',['Transaction',['../classcaffe2_1_1db_1_1_transaction.html',1,'caffe2::db']]],
  ['transform',['Transform',['../classcaffe2_1_1_transform.html',1,'caffe2']]],
  ['transposeop',['TransposeOp',['../classcaffe2_1_1_transpose_op.html',1,'caffe2']]],
  ['treecursor',['TreeCursor',['../classcaffe2_1_1dataset__ops_1_1_tree_cursor.html',1,'caffe2::dataset_ops']]],
  ['treeiterator',['TreeIterator',['../classcaffe2_1_1dataset__ops_1_1_tree_iterator.html',1,'caffe2::dataset_ops']]],
  ['treewalker',['TreeWalker',['../classcaffe2_1_1dataset__ops_1_1_tree_walker.html',1,'caffe2::dataset_ops']]],
  ['ttcontractiongradientop',['TTContractionGradientOp',['../classcaffe2_1_1_t_t_contraction_gradient_op.html',1,'caffe2']]],
  ['ttcontractionop',['TTContractionOp',['../classcaffe2_1_1_t_t_contraction_op.html',1,'caffe2']]],
  ['ttlineargradientop',['TTLinearGradientOp',['../classcaffe2_1_1_t_t_linear_gradient_op.html',1,'caffe2']]],
  ['ttlinearop',['TTLinearOp',['../classcaffe2_1_1_t_t_linear_op.html',1,'caffe2']]],
  ['ttpadgradientop',['TTPadGradientOp',['../classcaffe2_1_1_t_t_pad_gradient_op.html',1,'caffe2']]],
  ['ttpadop',['TTPadOp',['../classcaffe2_1_1_t_t_pad_op.html',1,'caffe2']]],
  ['type',['Type',['../struct_g_l_texture_1_1_type.html',1,'GLTexture']]],
  ['type',['type',['../group___neural_networks.html#gaebe0bf8514de064d1d68e8857a3dccfd',1,'ANeuralNetworksOperandType']]],
  ['typemeta',['TypeMeta',['../classcaffe2_1_1_type_meta.html#a9f8e66d75448302751da57b8df1c906f',1,'caffe2::TypeMeta::TypeMeta()'],['../classcaffe2_1_1_type_meta.html#aa110c2a289bafa97472342f25755a10f',1,'caffe2::TypeMeta::TypeMeta(const TypeMeta &amp;src)']]],
  ['typemeta',['TypeMeta',['../classcaffe2_1_1_type_meta.html',1,'caffe2']]],
  ['typename',['TypeName',['../classcaffe2_1_1_blob.html#a2a807ee90e38f2f0261f8c1f6709727a',1,'caffe2::Blob::TypeName()'],['../classcaffe2_1_1_type_meta.html#ac692ec187e8d53c6324e95ca0ac074a1',1,'caffe2::TypeMeta::TypeName()']]],
  ['typenameregisterer',['TypeNameRegisterer',['../structcaffe2_1_1_type_name_registerer.html',1,'caffe2']]],
  ['typenametraits',['TypeNameTraits',['../structcaffe2_1_1_type_name_traits.html',1,'caffe2']]],
  ['typenametraits_3c_20int32_5ft_20_3e',['TypeNameTraits&lt; int32_t &gt;',['../structcaffe2_1_1_type_name_traits_3_01int32__t_01_4.html',1,'caffe2']]],
  ['typenametraits_3c_20int64_5ft_20_3e',['TypeNameTraits&lt; int64_t &gt;',['../structcaffe2_1_1_type_name_traits_3_01int64__t_01_4.html',1,'caffe2']]]
];
